# Dataset / loader parameters
dataset_name: "mp"
data_path: /scratch/gpfs/ROSENGROUP/common/globus_share_OA/data/
label_path: /scratch/gpfs/ROSENGROUP/common/mp/chgcars
map_path: ./data/MP/map/map_sample.json.gz
rho_type: chgcar
functional: GGA
train_fraction: 0.5
random_state: 42
normalize_label: False
normalize_data: False
data_augmentation: True
label_size: [64, 64, 64]
data_size: [32, 32, 32]
data_precision: f32

# Model parameters
device: cuda:0
n_channels: 1 #32
n_residual_blocks: 1 #32
n_upscale_layers: 1
kernel_size1: 5
kernel_size2: 5
model_prefix: chk

# Training parameters
save_every_epochs: 2
epochs: 2
nbatch: 1
lr: 0.1
weight_decay: 0.0
