# Dataset / loader parameters
data:
  _target_: src.electrai.dataloader.dataset.RhoRead
  root: /scratch/gpfs/ROSENGROUP/common/globus_share_OA/mp/dataset_2/mp_filelist.txt
  split_file: null #/scratch/gpfs/ROSENGROUP/common/globus_share_OA/mp/dataset_1/split.json
  precision: f32
  batch_size: 1
  train_workers: 8
  val_workers: 2
  pin_memory: false
  val_frac: 0.005
  drop_last: false
  augmentation: false
  random_seed: 42
  # downsample_label: 0
  # downsample_data: 0

# Model
model:
  _target_: src.electrai.model.srgan_layernorm_pbc.GeneratorResNet
  n_residual_blocks: 32
  n_upscale_layers: 0
  n_channels: 32
  kernel_size1: 5
  kernel_size2: 5
  normalize: True
  use_checkpoint: False

# Training parameters
precision: 32
epochs: 50
lr: 0.01
weight_decay: 0.0
warmup_length: 1
beta1: 0.9
beta2: 0.99

# Weights and biases
wandb_mode: online
entity: PrinceOA
wb_pname: mp-experiment

# checkpoints
ckpt_path: ./checkpoints

# test the model
# save_pred: true
# log_dir: ./logs
# out_dir: ./predictions

